---
tomcat_web_root: /usr/share/tomcat/webapps/ROOT
app_server_packages:
  - tomcat
  - python-psycopg2
app_server_port: 8080
postgres_rhel7_repo: "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"

...

