---
- name: Gather instance info
  os_server_facts:
    cloud: openstack

- name: Delete instances
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    state: absent
  loop: "{{ openstack_servers }}"

...
