---
- hosts: localhost
  become: True
  gather_facts: False

  tasks:
    - name: Create bin directory under root
      file:
        path: /root/bin
        state: directory

    - name: Fetch script common.sh
      get_url:
        url: "{{ lookup('env','JQ_REPO_BASE') }}/scripts/common.sh"
        dest: /root/common.sh
        mode: 0755

    - name: Fetch script jq
      get_url:
        url: "{{ lookup('env','JQ_REPO_BASE') }}/scripts/jq-linux64"
        dest: /root/bin/jq
        mode: 0755

    - name: Fetch script order_svc.sh
      get_url:
        url: "{{ lookup('env','JQ_REPO_BASE') }}/scripts/order_svc.sh"
        dest: /root/order_svc.sh
        mode: 0755

    - name: Create credentials
      copy:
        content: |
          export username={{ lookup('env','OPENTLC_ID') }}
          export password={{ lookup('env','OPENTLC_PASSWORD') }}
          export uri=https://labs.opentlc.com
        dest: /root/credential.rc
        mode: 0755

    # Fix the existing shell scripts to reference jq command with bin/jq
    - name: Fix script references
      shell: "sed -i 's/ jq/ bin\\/jq/g' {{ item }}"
      with_items:
        - /root/common.sh
        - /root/order_svc.sh

    # Using this script will always deploy environments in the us-east-1 region.
    # TODO: this shell task is not working yet!
    - name: Order service on openTLC
      shell: source /root/credential.rc; ./order_svc.sh -y -c 'OPENTLC Automation' -i 'Ansible Advanced - Three Tier App' -t 1 -d 'dialog_expiration=7;region=na;nodes=1;dialog_runtime=8;notes=Training - As part of course'
      args:
        chdir: /root
    - name: Wait for mail
      pause:
        minutes: 10

...
