---
- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
      name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
      group: workstation

- hosts: workstation
  become: True
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yml 

...
