---
- name: Gather instance info
  os_server_facts:
    cloud: openstack
    region_name: regionOne
  register: __openstack_instances

- name: Add each gathered instance as host
  add_host:
    name: "{{ item.public_v4 }}"
    group:
      - "{{ item.metadata.group }}"
      - "{{ item.metadata.deployment_name }}"
  loop: "{{ __openstack_instances.ansible_facts.openstack_servers }}"
  # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
  # ansible_ssh_user: cloud-user

...
